// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPanel.Data;

#nullable disable

namespace MyPanel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251227105616_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("MyPanel.Models.Bot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuardCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActiveTm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFarmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradeLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("MyPanel.Models.Drop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DropDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSended")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.ToTable("Drops");
                });

            modelBuilder.Entity("MyPanel.Models.Drop", b =>
                {
                    b.HasOne("MyPanel.Models.Bot", null)
                        .WithMany("Drop")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPanel.Models.Bot", b =>
                {
                    b.Navigation("Drop");
                });
#pragma warning restore 612, 618
        }
    }
}
